background = 0xFF011627
base = 0xFF011627
text = 0xFFBDC1C6
bright_text = 0xFF080808
accent = 0xFFB2CEEE
font_size = 12
small_font_size = 11
icon_theme = Papirus-Dark
font_family = AdwaitaSans Regular
font_family_monospace = AdwaitaMono Nerd Font
